apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tdai-memory.fullname" . }}-core-config
  labels:
    {{- include "tdai-memory.labels" . | nindent 4 }}
data:
  tdai-gateway.yaml: |
    {{- include "tdai-memory.gatewayYaml" . | nindent 4 }}
